config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
  root "homes#index"

  resources :user do
    resources :languages
    resources :profiles, only: [:show, :edit, :update]
  end
end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :prof_pic, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/avatar.png"
  validates_attachment_content_type :prof_pic, content_type: /\Aimage\/.*\Z/
  has_attached_file :bg_pic, styles: { medium: "300x300>", large: "1000x1000>" }, default_url: "/assets/default_bg.png"
  validates_attachment_content_type :bg_pic, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :languages

  after_create :create_profile

  private
    def create_profile
      self.profile = Profile.create
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :language

  def index
  end

  def show
  end

  def new
  end

    private
    def language_params
      params.require(:language).permit(:string, :attachment)
    end

    def language
      @language = current_user.language
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :user
  before_action :profile, only: [:edit, :show]


  def show
  end

  def new
    @profile = current_user.profile.new
  end 

  def create
    @profile = current_user.profile.new(profile_params)
    if @profile.save
      flash[:notice] = "Profile created successfully."
      redirect_to user_profile_path(current_user, @profile)
    else 
      flash[:alert] = "Profile failed to save."
      render :new
    end
  end

  def edit
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      flash[:notice] = 'Profile updated successfully'
      redirect_to user_profile_path(current_user, @profile)
    else
      flash[:alert] = 'Profile failed to update.'
      render :edit
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:bio, :about_me, :prof_pic, :bg_pic, :gender, :age)
    end

    def profile
      @profile = current_user.profile
    end

    def user
      @user = current_user
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]



  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  #rIf you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

   def sign_up_params
     params.require(:user).permit(:first_name, :last_name, :email, :password,
     :password_confirmation)
   end

   def account_update_params
     params.require(:user).permit(:first_name, :last_name, :email, :password,
     :password_confirmation, :current_password)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_main.html.erb
<div class="col s12 m12 l8">
  <% if @users.any?  %>
    <% @users.each do |user| %>
      <% if user.profile && user.profile.bio %>
        <div class="row">
          <div class="card red darken-4 col s12 l8 offset-l2 med white-text">
            <div class="card-image waves-effect waves-block waves-light">
              <img style="height: 40em; "class="activator" src=<%= user.profile.bg_pic %>>
            </div>
            <div class="card-content red darken-4">
              <span class="card-title"><%= link_to user.first_name, user_profile_path(user, user.profile) %><i class="material-icons activator right">more_vert</i></span>
            </div>
            <div class="card-reveal grey darken-2">
              <span class="card-title "><%=user.first_name %><i class="material-icons right">close</i></span>
              <p><%= user.profile.bio %></p>
              <% if user.languages %>
                <% user.languages.each do |lang| %>
                  <%= lang.name %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="center white-text">
      <h1>Currently No Users</h1>
    </div>
  <% end %>
</div>

app/views/homes/_sidebar.html.erb
  <div class="languages">
    <div class="white-text col l3 hide-on-med-and-down grey darken-3">
      <ul class="fixed">
        <li>
          <img src="https://www.codementor.io/assets/topic/category_header/ruby-on-rails.png" class="picture">    <%= link_to 'RUBY' %>
        </li>
        <li>
          <img src="https://www.codementor.io/assets/page_img/learn-javascript.png" class="picture">    <%= link_to 'JAVASCRIPT' %>
        </li>
        <li>
          <img src="https://www.python.org/static/opengraph-icon-200x200.png" class="picture">    <%= link_to 'PYTHON' %>
        </li>
        <li>
          <img src="http://kukuruku.co/uploads/images/00/08/72/2015/04/09/7c8437.png" class="picture">    <%= link_to 'C++' %>
        </li>
        <li>
          <img src="http://devstickers.com/assets/img/pro/2p4i.png" class="picture">    <%= link_to 'C#' %>
        </li>
        <li>
          <img src="http://sqlcourseslondon.co.uk/wp-content/uploads/2015/08/badges_DD_Database_Stage3.png" class="picture">    <%= link_to 'SQL' %>
        </li>
        <li>
          <img src="http://www.iconarchive.com/download/i60803/graphics-vibe/developer/php.ico" class="picture">    <%= link_to 'PHP' %>
        </li>
      </ul>
    </div>
  </div>

app/views/homes/index.html.erb
<div class="row zero-margin">
  <%= render(partial: "sidebar") %>
  <%= render(partial: "main") %>
</div>

app/views/languages/index.html.erb
<h1>Languages#index</h1>
<p>Find me in app/views/languages/index.html.erb</p>

app/views/languages/new.html.erb
<h1>Languages#new</h1>
<p>Find me in app/views/languages/new.html.erb</p>

app/views/languages/show.html.erb
<h1>Languages#show</h1>
<p>Find me in app/views/languages/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hrefhack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper red darken-4 " >
        <a href="/" class="brand-logo" style="margin-top: .5em;">aHREF</a>
        <a href="" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="left hide-on-med-and-down right" style="margin-top: 2em;">
          <% if user_signed_in? && current_user.profile %>
            <li>
              <%= link_to current_user.first_name, user_profile_path(current_user, current_user.profile) %>
            </li>
            <li>
              <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %>
            </li>
          <% elsif user_signed_in? %>
            <li>
              <%= link_to current_user.first_name, new_user_profile_path(current_user) %>
            </li>
            <li>
              <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'LOGIN', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'SIGN UP', new_user_registration_path %>
            </li>
          <% end %>
        </ul>

        <ul class="left hide-on-large-only side-nav" id="mobile-demo" style="margin-top: 1em;">
          <% if user_signed_in? && current_user.profile %>
            <li><%= link_to current_user.first_name, user_profile_path(current_user, current_user.profile) %></li>
            <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
          <% elsif user_signed_in? %>
            <li><%= link_to current_user.first_name, new_user_profile_path(current_user) %></li>
            <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'LOGIN', new_user_session_path %></li>
            <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
          <% end %>
            <div class="divider"></div>
          <li class="black-text"><%= link_to 'RUBY' %></li>
          <li class="black-text"><%= link_to 'JAVASCRIPT' %></li>
          <li class="black-text"><%= link_to 'PYTHON' %></li>
          <li class="black-text"><%= link_to 'C++' %></li>
          <li class="black-text"><%= link_to 'C#' %></li>
          <li class="black-text"><%= link_to 'SQL' %></li>
          <li class="black-text"><%= link_to 'PHP' %></li>
        </ul>

      </div>
    </nav>
  </div>
  <p class="notice white-text"><%= notice %></p>
  <p class="alert white-text"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/profiles/edit.html.erb
<div class='container white-text'>
  <h1>Editing your profile</h1>

  <%= form_for [@user, @profile], html: { multipart: true } do |f| %>
    <%= f.text_field :bio, placeholder: 'Brief summary of who you are' %>
    <div class='file-field input-field'>
      <div class='btn'>
        <span>Profile Picture</span>
          <%= f.file_field :prof_pic %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <div class='file-field input-field'>
      <div class='btn'>
        <span>Background Picture</span>
          <%= f.file_field :bg_pic %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div class='row'>
      <div class='black-text col s4 offset 8'>
      <%= f.select :gender, ['--Select Gender--', 'Male', 'Female'], {}, placeholder: 'Gender', class: 'browser-default' %>
      </div>
    </div>
    <%= f.number_field :age, min: 16, max: 99, placeholder: 'Age', required: true %>
    <%= f.text_area :about_me, placeholder: 'Describe yourself in more depth' %>
    <button class='btn waves-effect' type="submit" name="action">
      Save Profile
    </button>
  <% end %>
</div>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/show.html.erb
  <div style="background: url(<%= @user.profile.bg_pic.url %>) no-repeat center center fixed; width: 100%; height: 800px; background-size: cover;"></div>
  <br/>
  <br/>

  <div class="firstbackground">
  <br/>
  <br/>
  <br/>
    <%= image_tag(@user.profile.prof_pic(:medium)) %>
    <br/>
    <br/>
    <div class="firstname">
      <%= @user.first_name %> <%= @user.last_name %>
      <p><%= @profile.about_me %>
      <%= @user.email %>
    </div>
    <br/>
  </div>

<div class="secondbackground">
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  Age: <%= @profile.age %>
  <br/>
  Gender: <%= @profile.gender %>
  <br/>
  <%= @profile.bio %>
</div>

<%= button_to 'Edit Profile', edit_user_profile_path(current_user, @profile), method: :get, class: 'btn'  %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>